name: Test Build

on:
  push:
    branches: [ main, develop ]  # master is handled by build-release.yml
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-build:
    name: Test Build on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          python3-pip \
          python3-gi \
          python3-gi-cairo \
          python3-dev \
          gir1.2-gtk-4.0 \
          wmctrl
          
    - name: Verify Python environment
      run: |
        echo "Python version: $(python3 --version)"
        echo "Python path: $(which python3)"
          
    - name: Test build process
      run: |
        echo "Testing build process..."
        ./ci-build.sh
        
    - name: Verify executable
      run: |
        echo "Verifying executable..."
        ls -lh dist/task-tracker
        file dist/task-tracker
        ./dist/task-tracker --help
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-build-task-tracker
        path: dist/task-tracker
        retention-days: 7